site_name: Learning
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Home: index.md
  - ToDo:
    - Frontend: todo/frontend.md
    - AI: todo/ai.md
markdown_extensions:
  - md_in_html
